### ISSUE TITLE
Beschreibungstexte für Anforderungen

### ISSUE THREAD

**Issue by bacheric** [gockelhahn/grundschmutz-tools#3]
Hi,

vielen Dank erstmal für die Arbeit hier, das ist super hilfreich um überhaupt an einen maschinenlesbaren Datensatz des BSI Kompendiums zu kommen.

Allerdings bräuchte ich nicht nur die Überschriften der Anforderungen, sondern auch deren Beschreibungstexte. Gibt es eine Möglichkeit, da den Parser soweit anzupassen, dass diese mit exportiert werden könnten?

**Comment by nitschSB** [comment]
Hi,
ich hatte das selbe Problem und bin daher bei [Vorgebirge/IT-Grundschutz](https://github.com/Vorgebirge/IT-Grundschutz/) gelandet. Da ist schon alles fertig.
Grüße

**Comment by bacheric** [comment]
Super, vielen Dank! Dann muss auch hier nicht der Scope dieses Projekts gesprengt werden.
